language: php

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

before_install:

script:
  - composer install
  - composer test
